#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
    rm /usr/sbin/<%= project_name %>
    rm /usr/sbin/<%= project_name %>-gem
fi

# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d <%= project_name %> remove >/dev/null
fi
# End automatically added section
